- name: "Browsers"
  description: "Browsers"
  hidden: false
  selected: false
  critical: false
  expanded: true
  packages:
    - chromium
    - falkon
    - firefox
    - midori
    - min
    - netsurf
    - opera
    - qutebrowser
    - torbrowser-launcher

- name: "Office"
  description: "Office Suites"
  hidden: false
  selected: false
  critical: false
  expanded: true
  packages:
    - libreoffice-still

- name: "Other"
  description: "Custom Software"
  hidden: false
  selected: false
  critical: false
  expanded: true
  packages:
    - catfish
    - leafpad
    - plank
    - spectacle
    - htop
    - nodejs
    - npm
    - gparted
    - baobab
    - simplescreenrecorder
    - libvirt
    - virt-manager
    - qemu
    - trello
    - postman-bin
    - github-desktop-bin
    - lastpass
    - spotify

- name: "Dependancies"
  description: "Packages used by other packages"
  hidden: false
  selected: false
  critical: false
  expanded: true
  packages:
    - gvfs
    - cron
    



