- name: "Browsers"
  description: "Browsers"
  hidden: false
  selected: false
  critical: false
  expanded: true
  packages:
    - chromium
    - falkon
    - firefox
    - midori
    - min
    - netsurf
    - opera
    - qutebrowser
    - torbrowser-launcher

- name: "Office"
  description: "Office Suites"
  hidden: false
  selected: false
  critical: false
  expanded: true
  packages:
    - libreoffice-still

